const htmlTopics = [
  { title: "HTML Tutorial", link: "/" },
  { title: "HTML Introduction", link: "/html-introduction" },
  { title: "HTML Editors", link: "/html-editors" },
  { title: "HTML Basics", link: "/html-basics" },
  { title: "HTML Comments", link: "/html-comments" },
  { title: "HTML Elements", link: "/html-elements" },
  { title: "HTML Attributes", link: "/html-attributes" },
  { title: "HTML Headings", link: "/html-headings" },
  { title: "HTML Paragraphs", link: "/html-paragraphs" },
  { title: "HTML Text Formatting", link: "/html-text-formatting" },
  { title: "HTML Quotations", link: "/html-quotations" },
  { title: "HTML Colors", link: "/html-colors" },
  { title: "HTML Links Hyperlinks", link: "/html-links" },
  { title: "HTML Images", link: "/html-images" },
  { title: "HTML Favicon", link: "/html-favicon" },
  { title: "HTML Tables", link: "/html-tables" },
  { title: "HTML List", link: "/html-list" },
  { title: "HTML Block and Inline Elements", link: "/html-block-inline" },
  { title: "HTML Iframes", link: "/html-iframes" },
  { title: "HTML File Paths", link: "/html-file-paths" },
  { title: "HTML Layout", link: "/html-layout" },
  { title: "HTML Computer Code Elements", link: "/html-computer-code" },
  { title: "HTML5 Semantics", link: "/html5-semantics" },
  { title: "HTML Entities", link: "/html-entities" },
  { title: "HTML Symbols", link: "/html-symbols" },
  { title: "HTML Emojis", link: "/html-emojis" },
  { title: "HTML Charsets", link: "/html-charsets" },
  { title: "HTML URL Encoding", link: "/html-url-encoding" },
  { title: "HTML Forms", link: "/html-forms" },
  { title: "HTML Responsive Web Design", link: "/html-responsive-design" },
  { title: "HTML Video", link: "/html-video" },
  { title: "HTML Examples", link: "/html-examples" },
  { title: "HTML Graphics", link: "/html-graphics" },
  { title: "HTML Tutorial References", link: "/html-tutorial-references" },
  {
    title: "HTML Exercises, Practice Questions and Solutions",
    link: "/html-exercises",
  },
];
export default htmlTopics;
